# Generated by Django 4.1.7 on 2023-07-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0003_reservationconfirmation_kkia_transaction_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment_status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
