# Generated by Django 4.1.7 on 2023-07-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0005_reservation_installment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='installment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='reservationconfirmation',
            name='kkia_transaction_code',
            field=models.CharField(default=1, max_length=100, null=True),
        ),
    ]
