# Generated by Django 4.1.7 on 2023-07-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0006_alter_reservation_installment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationconfirmation',
            name='kkia_transaction_code',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
