# Generated by Django 4.1.7 on 2023-07-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0010_remove_reservation_installment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='installment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
