# Generated by Django 4.1.7 on 2023-07-17 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0011_reservation_installment_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='installment_amount',
        ),
    ]
