# Generated by Django 4.1.7 on 2023-07-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0012_remove_reservation_installment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='installment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
