# Generated by Django 4.1.7 on 2023-07-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0013_reservation_installment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='installment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True),
        ),
    ]
