# Generated by Django 4.1.7 on 2023-07-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0015_alter_reservation_installment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationconfirmation',
            name='status',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
